# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Reminder

on:
  schedule:
    - cron: "0 10 * * THU"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
        env:
          RUNNER_TEMP: "/tmp/"
      - run: npm install
      - run: npm run reminder
        env:
          SLACK_AUTH_TOKEN: ${{ secrets.SLACK_AUTH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
