# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Unsolved

on:
  schedule:
    - cron: "0 1 * * MON"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: "unsolved"
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
        env:
          RUNNER_TEMP: "/tmp/"
      - run: npm install
      - run: npm run unsolved
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
